# Data source configuration
spring.data.mongodb.uri =  mongodb://localhost:27017/mystictourism
spring.data.mongodb.auto-index-creation=true
# Enabling PATCH, DELETE, PUT http methods
spring.mvc.hiddenmethod.filter.enabled=true

# JWT properties
security.jwt.secret-key= veryLongAndVerySecretKeyNoBodyWillEverGuessItBecauseItIsUnbelievablySecretOhMyLordSomeOneTryToGuessIt

# Redis configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379